server:
  port: 8888 # 端口
  tomcat:
    connection-timeout: 30000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud-disk?serverTiimezone=Asi/Shanghai&useUnicode=true&charaterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    default-property-inclusion: non_null # 忽略空值
    date-format: yyyy-MM-dd HH:mm:ss # 时间格式
    time-zone: GMT+8 # 时间域
  redis:
    port: 6379
    host: 192.168.136.160
  servlet:
    multipart:
      max-file-size: 20MB # 单个文件最大
      max-request-size: 30MB # 总文件最大
  main:
    allow-circular-references: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印日志
    map-underscore-to-camel-case: true # 映射下划线转驼峰
disk:
  sms:
    signName: 阿里云短信测试
    templateCode: SMS_154950909
    accessKey: LTAI5tCkyCK4WMPtyhvHP9zs
    secret: nKDJcFgQm6Vt2UGcMqWcTJR6HPwHMm
  oss:
    accessKey: LTAI5tCkyCK4WMPtyhvHP9zs
    secret: nKDJcFgQm6Vt2UGcMqWcTJR6HPwHMm
    endpoint: oss-cn-chengdu.aliyuncs.com
    bucketName: tanhua-wj
    url: https://tanhua-wj.oss-cn-chengdu.aliyuncs.com/

